"""add_employee_assessments_and_career_signals

Revision ID: 17dcf323081b
Revises: 3ef7227340f4
Create Date: 2026-07-12 18:52:52.378371

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "17dcf323081b"
down_revision: str | Sequence[str] | None = "3ef7227340f4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "career_signals",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.String(length=64), nullable=False),
        sa.Column("signal_type", sa.String(length=64), nullable=False),
        sa.Column("value", sa.String(length=128), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_career_signals_occurred_at"), "career_signals", ["occurred_at"], unique=False
    )
    op.create_index(op.f("ix_career_signals_user_id"), "career_signals", ["user_id"], unique=False)
    op.create_table(
        "employee_assessments",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.String(length=64), nullable=False),
        sa.Column("skills_inventory", sa.Text(), nullable=False),
        sa.Column("performance_level", sa.String(length=32), nullable=False),
        sa.Column("career_goals", sa.Text(), nullable=False),
        sa.Column("critical_role_interest", sa.Boolean(), nullable=False),
        sa.Column("consent_for_career_modeling", sa.Boolean(), nullable=False),
        sa.Column("raw_answers", sa.JSON(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_employee_assessments_user_id"), "employee_assessments", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_employee_assessments_user_id"), table_name="employee_assessments")
    op.drop_table("employee_assessments")
    op.drop_index(op.f("ix_career_signals_user_id"), table_name="career_signals")
    op.drop_index(op.f("ix_career_signals_occurred_at"), table_name="career_signals")
    op.drop_table("career_signals")
    # ### end Alembic commands ###
