"""initial schema

Revision ID: 3ef7227340f4
Revises: 
Create Date: 2026-07-08 11:56:04.082122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ef7227340f4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consent_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('purpose', sa.String(length=128), nullable=False),
    sa.Column('granted', sa.Boolean(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consent_records_user_id'), 'consent_records', ['user_id'], unique=False)
    op.create_table('ethical_decision_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('decision_type', sa.String(length=64), nullable=False),
    sa.Column('allowed', sa.Boolean(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('data_sources', sa.JSON(), nullable=False),
    sa.Column('classification', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ethical_decision_logs_user_id'), 'ethical_decision_logs', ['user_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('questionnaire_responses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('income_bracket', sa.String(length=32), nullable=False),
    sa.Column('goals', sa.Text(), nullable=False),
    sa.Column('risk_tolerance', sa.String(length=32), nullable=False),
    sa.Column('has_social_consent', sa.Boolean(), nullable=False),
    sa.Column('raw_answers', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_questionnaire_responses_user_id'), 'questionnaire_responses', ['user_id'], unique=False)
    op.create_table('spend_transactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_spend_transactions_category'), 'spend_transactions', ['category'], unique=False)
    op.create_index(op.f('ix_spend_transactions_occurred_at'), 'spend_transactions', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_spend_transactions_user_id'), 'spend_transactions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_spend_transactions_user_id'), table_name='spend_transactions')
    op.drop_index(op.f('ix_spend_transactions_occurred_at'), table_name='spend_transactions')
    op.drop_index(op.f('ix_spend_transactions_category'), table_name='spend_transactions')
    op.drop_table('spend_transactions')
    op.drop_index(op.f('ix_questionnaire_responses_user_id'), table_name='questionnaire_responses')
    op.drop_table('questionnaire_responses')
    op.drop_table('users')
    op.drop_index(op.f('ix_ethical_decision_logs_user_id'), table_name='ethical_decision_logs')
    op.drop_table('ethical_decision_logs')
    op.drop_index(op.f('ix_consent_records_user_id'), table_name='consent_records')
    op.drop_table('consent_records')
    # ### end Alembic commands ###
